// Prefissi telefonici internazionali (E.164), usati nel form di registrazione.
// I più rilevanti per il pubblico di Aura Ibiza (Italia, Spagna, e mercati
// europei principali) sono in cima; il resto segue in ordine alfabetico.
export const COUNTRY_CODES: { code: string; name: string; flag: string }[] = [
  { code: "+39", name: "Italia", flag: "🇮🇹" },
  { code: "+34", name: "Spagna", flag: "🇪🇸" },
  { code: "+44", name: "Regno Unito", flag: "🇬🇧" },
  { code: "+33", name: "Francia", flag: "🇫🇷" },
  { code: "+49", name: "Germania", flag: "🇩🇪" },
  { code: "+41", name: "Svizzera", flag: "🇨🇭" },
  { code: "+1", name: "USA / Canada", flag: "🇺🇸" },
  { code: "+93", name: "Afghanistan", flag: "🇦🇫" },
  { code: "+355", name: "Albania", flag: "🇦🇱" },
  { code: "+213", name: "Algeria", flag: "🇩🇿" },
  { code: "+376", name: "Andorra", flag: "🇦🇩" },
  { code: "+244", name: "Angola", flag: "🇦🇴" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+374", name: "Armenia", flag: "🇦🇲" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+43", name: "Austria", flag: "🇦🇹" },
  { code: "+994", name: "Azerbaigian", flag: "🇦🇿" },
  { code: "+1242", name: "Bahamas", flag: "🇧🇸" },
  { code: "+973", name: "Bahrein", flag: "🇧🇭" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+375", name: "Bielorussia", flag: "🇧🇾" },
  { code: "+32", name: "Belgio", flag: "🇧🇪" },
  { code: "+501", name: "Belize", flag: "🇧🇿" },
  { code: "+229", name: "Benin", flag: "🇧🇯" },
  { code: "+591", name: "Bolivia", flag: "🇧🇴" },
  { code: "+387", name: "Bosnia ed Erzegovina", flag: "🇧🇦" },
  { code: "+267", name: "Botswana", flag: "🇧🇼" },
  { code: "+55", name: "Brasile", flag: "🇧🇷" },
  { code: "+673", name: "Brunei", flag: "🇧🇳" },
  { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
  { code: "+226", name: "Burkina Faso", flag: "🇧🇫" },
  { code: "+257", name: "Burundi", flag: "🇧🇮" },
  { code: "+855", name: "Cambogia", flag: "🇰🇭" },
  { code: "+237", name: "Camerun", flag: "🇨🇲" },
  { code: "+238", name: "Capo Verde", flag: "🇨🇻" },
  { code: "+235", name: "Ciad", flag: "🇹🇩" },
  { code: "+56", name: "Cile", flag: "🇨🇱" },
  { code: "+86", name: "Cina", flag: "🇨🇳" },
  { code: "+357", name: "Cipro", flag: "🇨🇾" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+269", name: "Comore", flag: "🇰🇲" },
  { code: "+82", name: "Corea del Sud", flag: "🇰🇷" },
  { code: "+850", name: "Corea del Nord", flag: "🇰🇵" },
  { code: "+225", name: "Costa d'Avorio", flag: "🇨🇮" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+385", name: "Croazia", flag: "🇭🇷" },
  { code: "+53", name: "Cuba", flag: "🇨🇺" },
  { code: "+45", name: "Danimarca", flag: "🇩🇰" },
  { code: "+20", name: "Egitto", flag: "🇪🇬" },
  { code: "+503", name: "El Salvador", flag: "🇸🇻" },
  { code: "+971", name: "Emirati Arabi Uniti", flag: "🇦🇪" },
  { code: "+291", name: "Eritrea", flag: "🇪🇷" },
  { code: "+372", name: "Estonia", flag: "🇪🇪" },
  { code: "+251", name: "Etiopia", flag: "🇪🇹" },
  { code: "+679", name: "Figi", flag: "🇫🇯" },
  { code: "+63", name: "Filippine", flag: "🇵🇭" },
  { code: "+358", name: "Finlandia", flag: "🇫🇮" },
  { code: "+241", name: "Gabon", flag: "🇬🇦" },
  { code: "+220", name: "Gambia", flag: "🇬🇲" },
  { code: "+995", name: "Georgia", flag: "🇬🇪" },
  { code: "+233", name: "Ghana", flag: "🇬🇭" },
  { code: "+81", name: "Giappone", flag: "🇯🇵" },
  { code: "+962", name: "Giordania", flag: "🇯🇴" },
  { code: "+30", name: "Grecia", flag: "🇬🇷" },
  { code: "+299", name: "Groenlandia", flag: "🇬🇱" },
  { code: "+590", name: "Guadalupa", flag: "🇬🇵" },
  { code: "+502", name: "Guatemala", flag: "🇬🇹" },
  { code: "+224", name: "Guinea", flag: "🇬🇳" },
  { code: "+245", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "+240", name: "Guinea Equatoriale", flag: "🇬🇶" },
  { code: "+592", name: "Guyana", flag: "🇬🇾" },
  { code: "+509", name: "Haiti", flag: "🇭🇹" },
  { code: "+504", name: "Honduras", flag: "🇭🇳" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+98", name: "Iran", flag: "🇮🇷" },
  { code: "+964", name: "Iraq", flag: "🇮🇶" },
  { code: "+353", name: "Irlanda", flag: "🇮🇪" },
  { code: "+354", name: "Islanda", flag: "🇮🇸" },
  { code: "+972", name: "Israele", flag: "🇮🇱" },
  { code: "+1876", name: "Giamaica", flag: "🇯🇲" },
  { code: "+254", name: "Kenya", flag: "🇰🇪" },
  { code: "+996", name: "Kirghizistan", flag: "🇰🇬" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+371", name: "Lettonia", flag: "🇱🇻" },
  { code: "+961", name: "Libano", flag: "🇱🇧" },
  { code: "+231", name: "Liberia", flag: "🇱🇷" },
  { code: "+218", name: "Libia", flag: "🇱🇾" },
  { code: "+423", name: "Liechtenstein", flag: "🇱🇮" },
  { code: "+370", name: "Lituania", flag: "🇱🇹" },
  { code: "+352", name: "Lussemburgo", flag: "🇱🇺" },
  { code: "+853", name: "Macao", flag: "🇲🇴" },
  { code: "+389", name: "Macedonia del Nord", flag: "🇲🇰" },
  { code: "+261", name: "Madagascar", flag: "🇲🇬" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+265", name: "Malawi", flag: "🇲🇼" },
  { code: "+960", name: "Maldive", flag: "🇲🇻" },
  { code: "+223", name: "Mali", flag: "🇲🇱" },
  { code: "+356", name: "Malta", flag: "🇲🇹" },
  { code: "+212", name: "Marocco", flag: "🇲🇦" },
  { code: "+230", name: "Mauritius", flag: "🇲🇺" },
  { code: "+52", name: "Messico", flag: "🇲🇽" },
  { code: "+373", name: "Moldova", flag: "🇲🇩" },
  { code: "+377", name: "Monaco", flag: "🇲🇨" },
  { code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { code: "+258", name: "Mozambico", flag: "🇲🇿" },
  { code: "+95", name: "Myanmar", flag: "🇲🇲" },
  { code: "+264", name: "Namibia", flag: "🇳🇦" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+505", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+227", name: "Niger", flag: "🇳🇪" },
  { code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { code: "+47", name: "Norvegia", flag: "🇳🇴" },
  { code: "+64", name: "Nuova Zelanda", flag: "🇳🇿" },
  { code: "+968", name: "Oman", flag: "🇴🇲" },
  { code: "+31", name: "Paesi Bassi", flag: "🇳🇱" },
  { code: "+92", name: "Pakistan", flag: "🇵🇰" },
  { code: "+507", name: "Panama", flag: "🇵🇦" },
  { code: "+595", name: "Paraguay", flag: "🇵🇾" },
  { code: "+51", name: "Perù", flag: "🇵🇪" },
  { code: "+48", name: "Polonia", flag: "🇵🇱" },
  { code: "+689", name: "Polinesia Francese", flag: "🇵🇫" },
  { code: "+351", name: "Portogallo", flag: "🇵🇹" },
  { code: "+974", name: "Qatar", flag: "🇶🇦" },
  { code: "+40", name: "Romania", flag: "🇷🇴" },
  { code: "+250", name: "Ruanda", flag: "🇷🇼" },
  { code: "+7", name: "Russia / Kazakistan", flag: "🇷🇺" },
  { code: "+685", name: "Samoa", flag: "🇼🇸" },
  { code: "+378", name: "San Marino", flag: "🇸🇲" },
  { code: "+221", name: "Senegal", flag: "🇸🇳" },
  { code: "+381", name: "Serbia", flag: "🇷🇸" },
  { code: "+248", name: "Seychelles", flag: "🇸🇨" },
  { code: "+232", name: "Sierra Leone", flag: "🇸🇱" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+421", name: "Slovacchia", flag: "🇸🇰" },
  { code: "+386", name: "Slovenia", flag: "🇸🇮" },
  { code: "+252", name: "Somalia", flag: "🇸🇴" },
  { code: "+27", name: "Sudafrica", flag: "🇿🇦" },
  { code: "+249", name: "Sudan", flag: "🇸🇩" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+46", name: "Svezia", flag: "🇸🇪" },
  { code: "+963", name: "Siria", flag: "🇸🇾" },
  { code: "+992", name: "Tagikistan", flag: "🇹🇯" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+255", name: "Tanzania", flag: "🇹🇿" },
  { code: "+66", name: "Thailandia", flag: "🇹🇭" },
  { code: "+228", name: "Togo", flag: "🇹🇬" },
  { code: "+216", name: "Tunisia", flag: "🇹🇳" },
  { code: "+90", name: "Turchia", flag: "🇹🇷" },
  { code: "+993", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "+380", name: "Ucraina", flag: "🇺🇦" },
  { code: "+256", name: "Uganda", flag: "🇺🇬" },
  { code: "+36", name: "Ungheria", flag: "🇭🇺" },
  { code: "+598", name: "Uruguay", flag: "🇺🇾" },
  { code: "+998", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+967", name: "Yemen", flag: "🇾🇪" },
  { code: "+260", name: "Zambia", flag: "🇿🇲" },
  { code: "+263", name: "Zimbabwe", flag: "🇿🇼" },
];
